### ISSUE TITLE
Package was removed from the registry by the npm security team.

### ISSUE THREAD

**Issue by odys-z** [jitsi/eslint-config-jitsi#17]
Hello,

I'm following this [handbook](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual#deploy-jitsi-meet) to install a jitsi meet server as both the docker & ubuntu ways failed.

When installing npm packages required by "Deploy Jitsi Meet", 

````
    npm install
````

It's halted on 

```
    [            ......] \ extract:eslint-config-jitsi: sill extract github:jitsi/
```

Checking at [NPM page](https://www.npmjs.com/package/eslint-config-jitsi), it's been removed.

All I want is try to host a server. Now what?

![npm packege removed](https://github.com/odys-z/hello/blob/master/jitsi/imgs/00-npm-removed.jpg?raw=true)

FYI. As I don't have Ubuntu 18, I'm trying this on a Docker container of Ubutun 20.04

**Comment by damencho** [comment]
That package is being used directly from github: https://github.com/jitsi/jitsi-meet/blob/ae9bea1a0cb4d884edd9e0b7bac93bfa4c8021b9/package.json#L129 and should not have problems downloading it from there.

The manual that you are following has a Warning check it out. Those instructions are known to be outdated and you will have many problems to make all components run. Try the quick install guide or the docker images.

**Comment by damencho** [comment]
We do not use that package from the npm registry. The npm registry placed an empty package there so nobody can use the same name.
