### ISSUE TITLE
ESLint Plugins and Parser not declared as Peer Dependency

### ISSUE THREAD

**Issue by akshitkrnagpal** [jitsi/eslint-config-jitsi#2]
If `eslint-plugin-flowtype` , `eslint-plugin-import` and `babel-eslint` are declared as peer dependency, developers will be notified to install them.

**Comment by saghul** [comment]
Sounds good to me. @hristoterezov WDYT?

**Comment by saghul** [comment]
Closing since we decided we solve that with documentation.
